// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpgnaccdpzvcmftmqtig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ25hY2NkcHp2Y21mdG1xdGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMDY4ODQsImV4cCI6MjA1Njc4Mjg4NH0.A7Ukz84ADZPqmRt71hWyJl01xKy0VATUQSWfeRLzEfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);